keys:
  # Admin key - Mykhailo's GPG key
  - &admin_mykhailo C33BFD3230B660CF147762D2BF5C81B531164955

  # System keys (add via: ssh-keyscan hostname | ssh-to-age)
  # - &potato age1...
  # - &muscle age1...

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *admin_mykhailo
      # age:
      # - *potato
      # - *muscle

