keys:
  - &pgp_fingerprint C33BFD3230B660CF147762D2BF5C81B531164955
  - &tomato age1t658m4yv4q3sfpfu8y458lv963y2lmtlqkhkezgndzk0pu8xvvyq3rsvzw
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *pgp_fingerprint
        age:
          - *tomato
