keys:
  - &pgp_fingerprint C33BFD3230B660CF147762D2BF5C81B531164955
  - &tomato age1a26rq52n42wn9u8436led7hspc7tny6w26mc8a32qyg3puv4j4vs7at72w
  - &pickle age1z4v4t3s0vmsvwvvmzrrss57hyl0h4al4wsz3jv5zufk6r9qmzggqfsuz4a
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *pgp_fingerprint
        age:
          - *tomato
          - *pickle
