keys:
  - &mykhailo C33BFD3230B660CF147762D2BF5C81B531164955

  # System SSH host keys (get via: ssh-to-age)
  # Commands to get your system keys:
  #   Local:  nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
  #   Remote: nix-shell -p ssh-to-age --run 'ssh-keyscan muscle.local | ssh-to-age'

  - &tomato age1q2w3f6zzt7tgykpy8av47k9xv5lmqthq2yvg7pv3xaa8xzh8lf8qs4zzu0
  - &pickle age1qrvvl2k5jlhe8kr5ng2003vfc7xw5fl4eqt0j3js0luttzv8qsmszey5gp
  - &potato age162xgj9syl0k3fhre4gjc2e4m0vatcz2dw3zw0l65rhqf9mdgvy0s0jaw8t

  - &media age1qunw4q04cdg2lzaagkxjkr2gee8kyhxr9l6fsfd5wgm0d2w2tpcsqe8zuw
  - &ipfs age10k62z44u66nw4f3y9qjjf0k36rxv5fd23p0plsrmwem55frpaevsnuwc3p
  - &muscle age1qeflxvwq07z0r70mgunmgxdkclkm324m9t8wjefqqrvwz4lpluhqwpjf05
  - &beefy age1yfuufkuzey2fvda2slpz3wwyz7suf6f4chha9u7a4hs8gfynr5ds7npram

creation_rules:
  - path_regex: nix/lib/builders/secrets\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *mykhailo
      age:
      - *tomato
      - *pickle
      - *potato
      - *muscle
      - *beefy
      - *media
      - *ipfs
  - path_regex: secrets.*\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *mykhailo
      age:
      - *tomato
      - *pickle
      - *potato
      - *muscle
      - *media
      - *ipfs

