keys:
  - &pgp_fingerprint C33BFD3230B660CF147762D2BF5C81B531164955
  - &tomato age1dzqkau3k38cclp6rw6hlhzp99d9gruv7u4rg2vcry9krze9ry97qemuqvm
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *pgp_fingerprint
        age:
          - *tomato
