#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
if [[ -n "$(git status --porcelain)" ]]; then
    echo "Error: Git working directory is not clean. Please commit or stash changes first."
    exit 1
fi

nix flake archive --json "$NIX_OPTIONS" \
  | jq -r '.path,(.inputs|to_entries[].value.path)' \
  | cachix push land

if [[ "$(uname -m)" == "arm64" ]] && [[ "$(uname -s)" == "Darwin" ]]; then
  nix build .#darwinConfigurations.common.system --json "$NIX_OPTIONS" \
    | jq -r '.[].outputs | to_entries[].value' \
    | cachix push land
fi

if [[ "$(uname -m)" == "x86_64" ]] && [[ "$(uname -s)" == "Linux" ]]; then
  nix build .#nixosConfigurations.tomato.config.system.build.toplevel --json "$NIX_OPTIONS" \
    | jq -r '.[].outputs | to_entries[].value' \
    | cachix push land
fi
