name: Nix Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        system:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v12
        with:
          name: land
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: HatsuneMiku3939/direnv-action@v1
        with:
          direnvVersion: 2.32.1
      - name: Push to Cachix
        run: ./scripts/cachix-push
